const os=require('os');
const user=os.userInfo();
console.log(user);
console.log(os.EOL);
console.log('Architecture:',os.arch());
console.log('cpus:',os.cpus());
console.log('endianness:',os.endianness());
console.log('freemem:',os.freemem());
console.log('homedir:',os.homedir());
console.log('hosname:',os.hostname());
console.log('loadavg:',os.loadavg());
console.log('machine:',os.machine());
console.log('networkInterfaces:',os.networkInterfaces());
console.log('platform:',os.platform());
console.log('release:',os.release());
console.log('tmpdir:',os.tmpdir());
console.log('totalmem:',os.totalmem());
console.log('type:',os.type());
console.log('uptime:',os.uptime());
console.log('version:',os.version());